;; cider
(unless (package-installed-p 'cider)
  (package-install 'cider))
(unless (package-installed-p 'ac-cider)
  (package-install 'ac-cider))
(unless (package-installed-p 'clj-refactor)
  (package-install 'clj-refactor))
(unless (package-installed-p 'cljr-helm)
  (package-install 'cljr-helm))
(unless (package-installed-p 'clojure-mode)
  (package-install 'clojure-mode))
(unless (package-installed-p 'clojure-mode-extra-font-locking)
  (package-install 'clojure-mode-extra-font-locking))
;; (unless (package-installed-p 'clojure-quick-repls)
;;   (package-install 'clojure-quick-repls))
(unless (package-installed-p 'paredit)
  (package-install 'paredit))
(unless (package-installed-p 'paren-completer)
  (package-install 'paren-completer))
(unless (package-installed-p 'rainbow-delimiters)
  (package-install 'rainbow-delimiters))
